Added some documentation. Added is function.

diff --git a/.bashrc.d/00_functions b/.bashrc.d/00_functions
--- a/.bashrc.d/00_functions
+++ b/.bashrc.d/00_functions
@@ -1,4 +1,25 @@
-#!/usr/bin/env bash
+# ~/.bashrc.d/01_functions
+#
+
+is() {
+  cmd="$1"; shift
+  case $cmd in
+    not)
+      ! is "$@" ;;
+    installed)
+      hash "$@" 2> /dev/null ;;
+    file)
+      test -f "$@" ;;
+    executable)
+      test -x "$@" ;;
+    dir)
+      test -d "$@" ;;
+    *)
+      echo -e "is error: \n\t$cmd command not implemented" >&2
+      return 1
+  esac
+}
+
 is_wsl() {
   grep -q Microsoft /proc/version
 }
